---
AllCops:
    Exclude:
        - '**/*.gemspec'
        - 'tmp/**/*'
        - 'pkg/**/*'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/BlockLength:
  Enabled: false
  Exclude: 
    - spec/unit/**/*

Metrics/MethodLength:
  Max: 20

Style/AccessorMethodName:
  Enabled: False

Style/HashSyntax:
  Enabled: false

Style/SignalException:
  Enabled: False

Style/GuardClause:
  Enabled: False

Metrics/PerceivedComplexity:
  Max: 20 

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 130

Lint/UselessAssignment:
  Enabled: False

Lint/BooleanSymbol:
  Enabled: false
